---
apiVersion: v1
kind: Namespace
metadata:
  name: nla
---
apiVersion: v1
kind: Service
metadata:
  namespace: nla
  name: minio-190-service
spec:
  selector:
    app: blabla
  ports:
    - name: minio
      protocol: TCP
      port: 9000
      targetPort: 9000
  type: NodePort
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-190-pvc
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: ./data/190

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: nla
  name: minio-190-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nla
  name: lab-190-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blabla
  template:
    metadata:
      labels:
        app: blabla
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: minio-190-pvc
      containers:
        - name: my-minio-fs
          volumeMounts:
            - name: data 
              mountPath: "/data"
          image: minio/minio:RELEASE.2017-11-22T19-55-46Z
          args:
            - server
            - /data
          env:
            - name: MINIO_ACCESS_KEY
              value: dasdasdas
            - name: MINIO_SECRET_KEY
              value: dasdasdasdasdas

